=head1 NAME

Jonk2::Cookbook::LookupSpecificJob - lookup specific job.

=head1 USAGE

    #! perl
    use strict;
    use warnings;
    use DBI;
    use Jonk2;
    
    my $dbh = DBI->connect('dbi:mysql:test','user','pass');
    
    my $jonk = Jonk2->new($dbh, {functions => [qw/worker_key/]});
    my $job_id = $jonk->insert('worker_key','job_data_here');

    my $job = $jonk->lookup_job($job_id);

=cut
